import { Clock, Copy, Rss, Save, Sparkles, Zap } from "lucide-react";

const features = [
  {
    icon: Rss,
    title: "RSS Feed Aggregation",
    description:
      "Connect multiple RSS feeds from our curated collection or add custom URLs. Automatically fetch and organize content from all your sources.",
    gradient: "from-blue-500 to-cyan-500",
  },
  {
    icon: Sparkles,
    title: "AI-Powered Generation",
    description:
      "Get 5 newsletter titles, 5 subject lines, and a complete newsletter body generated by advanced AI in seconds.",
    gradient: "from-purple-500 to-pink-500",
  },
  {
    icon: Save,
    title: "Newsletter History",
    description:
      "Save and access all past newsletters. Never lose your content and reuse successful formats anytime.",
    gradient: "from-emerald-500 to-teal-500",
  },
  {
    icon: Clock,
    title: "Custom Time Ranges",
    description:
      "Generate newsletters for any timeframe - weekly, monthly, or custom date ranges. Perfect for any publishing schedule.",
    gradient: "from-orange-500 to-amber-500",
  },
  {
    icon: Zap,
    title: "Top Announcements",
    description:
      "AI automatically curates the top 5 most important news items from your content sources for quick highlights.",
    gradient: "from-rose-500 to-red-500",
  },
  {
    icon: Copy,
    title: "Copy & Paste Ready",
    description:
      "Export perfectly formatted content ready to paste into any email platform. Works with Mailchimp, ConvertKit, Substack, and more.",
    gradient: "from-violet-500 to-indigo-500",
  },
];

export function Features() {
  return (
    <section id="features" className="py-24 sm:py-32 bg-[#0a0f1a] relative">
      {/* Background pattern */}
      <div className="absolute inset-0 grid-pattern" />
      
      <div className="relative mx-auto max-w-7xl px-6 lg:px-8">
        <div className="mx-auto max-w-2xl text-center">
          <span className="text-blue-400 font-semibold text-sm uppercase tracking-wider">Features</span>
          <h2 className="mt-2 text-3xl font-bold tracking-tight text-white sm:text-4xl">
            Everything You Need to Create{" "}
            <span className="premium-gradient-text">Amazing Newsletters</span>
          </h2>
          <p className="mt-4 text-lg text-slate-400">
            Powerful features designed specifically for newsletter creators who
            value their time
          </p>
        </div>

        <div className="mx-auto mt-16 grid max-w-7xl grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3">
          {features.map((feature) => {
            const Icon = feature.icon;
            return (
              <div
                key={feature.title}
                className="group relative rounded-xl glass-card p-6 transition-all duration-300 hover:scale-[1.02] hover:shadow-xl hover:shadow-blue-500/10"
              >
                {/* Icon */}
                <div className={`mb-4 inline-flex size-12 items-center justify-center rounded-lg bg-gradient-to-br ${feature.gradient} text-white shadow-lg`}>
                  <Icon className="size-6" />
                </div>
                
                {/* Content */}
                <h3 className="text-xl font-semibold text-white mb-2">
                  {feature.title}
                </h3>
                <p className="text-slate-400 text-sm leading-relaxed">
                  {feature.description}
                </p>
                
                {/* Hover gradient line */}
                <div className={`absolute bottom-0 left-0 right-0 h-0.5 bg-gradient-to-r ${feature.gradient} opacity-0 group-hover:opacity-100 transition-opacity rounded-b-xl`} />
              </div>
            );
          })}
        </div>
      </div>
    </section>
  );
}
